name: CI

on:
  push:
    branches: [release/*, develop]
  pull_request:
    branches: [release/*, develop]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20.x"
  SKIP_DEPLOY: false

jobs:
  setup:
    name: Setup Node.js and Dependencies
    runs-on: ubuntu-latest
    outputs:
      node-version: ${{ steps.node.outputs.node-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve Node.js and dependencies
        uses: ./.github/actions/setup

      - name: Set Node.js version output
        id: node
        run: echo "node-version=${{ env.NODE_VERSION }}" >> $GITHUB_OUTPUT

  lint:
    name: Lint
    needs: setup
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    strategy:
      matrix:
        task: [lint, check-types]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Retrieve Node.js and dependencies
        uses: ./.github/actions/setup

      - name: Run ${{ matrix.task }}
        run: yarn turbo run ${{ matrix.task }} --filter='...[HEAD^1]'

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    strategy:
      matrix:
        task: [test, test:coverage]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Retrieve Node.js and dependencies
        uses: ./.github/actions/setup

      - name: Run ${{ matrix.task }}
        run: yarn turbo run ${{ matrix.task }} --filter='...[HEAD^1]'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Retrieve Node.js and dependencies
        uses: ./.github/actions/setup

      - name: Build applications
        run: |
          yarn turbo run build:dev --filter='...[HEAD^1]'

        env:
          NODE_ENV: development
          NEXT_PUBLIC_RUN_ENVIRONMENT: development(.env)

          SLS_STAGE: dev
          SLS_KEY_ALARM: ${{ secrets.SLS_KEY_ALARM }}
          SLS_DB_NAME: ${{ secrets.SLS_DB_NAME }}
          SLS_DB_PASSWORD: ${{ secrets.SLS_DB_PASSWORD }}
          SLS_DB_USERNAME: ${{ secrets.SLS_DB_USERNAME }}
          SLS_GIF_API_KEY: ${{ secrets.SLS_GIF_API_KEY }}
          SLS_GIF_ENDPOINT: ${{ secrets.SLS_GIF_ENDPOINT }}
          SLS_IA_API_KEY: ${{ secrets.SLS_IA_API_KEY }}
          SLS_IMG_ACCESS_KEY: ${{ secrets.SLS_IMG_ACCESS_KEY }}
          SLS_IMG_ENDPOINT: ${{ secrets.SLS_IMG_ENDPOINT }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
